-- LibraryOfBabel Metadata Cleanup SQL
-- Generated by Dr. Sarah Chen's Metadata Cleanup Analyzer
-- Execute with caution - backup database first

-- Author Fixes
UPDATE books SET author = 'John Green Conversation - Daily Books' WHERE book_id = 129; -- was: 'Unknown'
UPDATE books SET author = 'Trivion Books' WHERE book_id = 238; -- was: 'Unknown'
UPDATE books SET author = 'Bradley B Onishi' WHERE book_id = 334; -- was: 'Unknown'
UPDATE books SET author = 'Redgrave' WHERE book_id = 412; -- was: 'Unknown'
UPDATE books SET author = 'Natalie Y  Gutierrez Jennifer Mullan' WHERE book_id = 508; -- was: 'Unknown'
UPDATE books SET author = 'Danie Ware Alec Worley and Phil Kelly' WHERE book_id = 644; -- was: 'Various'
UPDATE books SET author = 'Various Authors' WHERE book_id = 838; -- was: 'Various'
UPDATE books SET author = 'Child Lee' WHERE book_id = 975; -- was: 'Unknown'
UPDATE books SET author = 'Celeste Ng - Trivion Books' WHERE book_id = 1258; -- was: 'Unknown'
UPDATE books SET author = 'dailyBooks' WHERE book_id = 1666; -- was: 'Unknown'
UPDATE books SET author = 'Dick Philip K Kaufman Charlie' WHERE book_id = 2082; -- was: 'Unknown'
UPDATE books SET author = 'dailyBooks' WHERE book_id = 2089; -- was: 'Unknown'
UPDATE books SET author = 'Proust Marcel' WHERE book_id = 2099; -- was: 'Unknown'
UPDATE books SET author = 'Manly Palmer Hall' WHERE book_id = 2111; -- was: 'Unknown'
UPDATE books SET author = 'Rainbow Rowell 2 Books - Rainbow Rowell Attachments By Rainbow Rowell' WHERE book_id = 2150; -- was: 'Unknown'
UPDATE books SET author = 'Said Edward W ' WHERE book_id = 2183; -- was: 'Unknown'
UPDATE books SET author = 'Marcel Proust' WHERE book_id = 2291; -- was: 'Unknown'
UPDATE books SET author = 'John D  Kelleher Brian Mac Namee Aoife DArcy' WHERE book_id = 2483; -- was: 'Unknown'
UPDATE books SET author = 'Liu Ken' WHERE book_id = 2511; -- was: 'Unknown'
UPDATE books SET author = 'Huxley Aldous' WHERE book_id = 2512; -- was: 'Unknown'

-- Single-Word Author Fixes
UPDATE books SET author = 'Butler Octavia' WHERE book_id = 128; -- was: 'Dawn' (suspicious_metadata_issue)
UPDATE books SET author = 'Wiesner Karen' WHERE book_id = 236; -- was: 'Lace' (suspicious_metadata_issue)
UPDATE books SET author = 'Martin Ph D  Wednesday' WHERE book_id = 1141; -- was: 'Martin,Wednesday' (potential_extraction_error)
UPDATE books SET author = 'Brown Dee' WHERE book_id = 2042; -- was: 'Nancy' (potential_extraction_error)
UPDATE books SET author = 'Stephen Baxter' WHERE book_id = 131; -- was: 'Raft' (suspicious_metadata_issue)
UPDATE books SET author = 'Shusterman Neal' WHERE book_id = 143; -- was: 'Unwind' (potential_extraction_error)
UPDATE books SET author = 'Santlofer Jonathan editor Russo Richard Russo' WHERE book_id = 1665; -- was: 'Vi' (potential_extraction_error)
UPDATE books SET author = 'Ziwe Fumudoh' WHERE book_id = 184; -- was: 'Ziwe' (potential_extraction_error)
UPDATE books SET author = 'Kowal Mary Robinette' WHERE book_id = 55; -- was: 'cj5' (potential_extraction_error)

-- Title Fixes
UPDATE books SET title = 'The Doors of Perception Heaven and Hell Two Complete' WHERE book_id = 2512; -- was: 'Unknown Title'