-- LibraryOfBabel Metadata Cleanup SQL (Refined)
-- Generated by Dr. Sarah Chen's Metadata Cleanup Analyzer (Manual Review)
-- Execute with caution - backup database first

-- High-Confidence Author Fixes (Reviewed & Refined)

-- Clear Unknown → Real Authors (from filenames)
UPDATE books SET author = 'Bradley B. Onishi' WHERE book_id = 334; -- was: 'Unknown'
UPDATE books SET author = 'Lee Child' WHERE book_id = 975; -- was: 'Unknown' 
UPDATE books SET author = 'Marcel Proust' WHERE book_id = 2099; -- was: 'Unknown'
UPDATE books SET author = 'Manly Palmer Hall' WHERE book_id = 2111; -- was: 'Unknown'
UPDATE books SET author = 'Marcel Proust' WHERE book_id = 2291; -- was: 'Unknown'
UPDATE books SET author = 'Edward W. Said' WHERE book_id = 2183; -- was: 'Unknown'
UPDATE books SET author = 'Ken Liu' WHERE book_id = 2511; -- was: 'Unknown'
UPDATE books SET author = 'Aldous Huxley' WHERE book_id = 2512; -- was: 'Unknown'

-- Clear Single-Word Issues → Proper Names
UPDATE books SET author = 'Octavia Butler' WHERE book_id = 128; -- was: 'Dawn' (book title used as author)
UPDATE books SET author = 'Stephen Baxter' WHERE book_id = 131; -- was: 'Raft' (book title used as author)
UPDATE books SET author = 'Neal Shusterman' WHERE book_id = 143; -- was: 'Unwind' (book title used as author)
UPDATE books SET author = 'Karen Wiesner' WHERE book_id = 236; -- was: 'Lace' (book title used as author)

-- Fix Name Format Issues
UPDATE books SET author = 'Wednesday Martin' WHERE book_id = 1141; -- was: 'Martin,Wednesday'
UPDATE books SET author = 'Dee Brown' WHERE book_id = 2042; -- was: 'Nancy' (wrong extraction)
UPDATE books SET author = 'Ziwe Fumudoh' WHERE book_id = 184; -- was: 'Ziwe' (incomplete name)

-- Multi-Author Books (keep but clean up)
UPDATE books SET author = 'John D. Kelleher, Brian Mac Namee, Aoife D''Arcy' WHERE book_id = 2483; -- was: 'Unknown'
UPDATE books SET author = 'Natalie Y. Gutierrez, Jennifer Mullan' WHERE book_id = 508; -- was: 'Unknown'
UPDATE books SET author = 'Philip K. Dick, Charlie Kaufman' WHERE book_id = 2082; -- was: 'Unknown'

-- Title Fixes
UPDATE books SET title = 'The Doors of Perception & Heaven and Hell' WHERE book_id = 2512; -- was: 'Unknown Title'

-- Notes for manual review (these need human verification):
-- Book 129: 'The Fault In Our Stars' - real author is John Green, not "John Green Conversation - Daily Books"
-- Book 238: 'Zero To One' - real author is Peter Thiel, not "Trivion Books"  
-- Book 1258: 'Everything I Never Told You' - real author is Celeste Ng, not "Celeste Ng - Trivion Books"
-- Book 1666: 'I'm Still Here' - real author is Austin Channing Brown, not "dailyBooks"
-- Book 2089: 'Braiding Sweetgrass' - real author is Robin Wall Kimmerer, not "dailyBooks"
-- Book 2150: 'Eleanor & Park' - real author is Rainbow Rowell, not the long filename string

-- Summary: 
-- Applied 18 high-confidence fixes
-- Flagged 6 books for manual review (publisher/discussion guide books misattributed)